---

  version: '3'

  services:

    db:
      image: postgres:13.0-alpine
      container_name: db
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE}
      volumes:
        - pgdata:/var/lib/postgresql/data

    app:
      build: .
      container_name: app
      volumes:
        - .:/app
      depends_on:
        - db

    web:
      image: nginx:1.19-alpine
      container_name: web
      ports:
        - "3000:80"
      volumes:
        - .:/app
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - app

  volumes:
    pgdata:
